[package]
name = "aoc-2022-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc-main = { version = "0.5.0", features = ["bench"] }
aoc-parse = "0.1.9"
num-modular = "0.5.1"
rayon = "1.6.1"
